//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krisa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krisa.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se admiten solo letras.
        /// </summary>
        public static string CAMPO_LETRAS {
            get {
                return ResourceManager.GetString("CAMPO_LETRAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se admiten solo letras y numeros.
        /// </summary>
        public static string CAMPO_LETRASYNUMEROS {
            get {
                return ResourceManager.GetString("CAMPO_LETRASYNUMEROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo requerido.
        /// </summary>
        public static string CAMPO_VACIO {
            get {
                return ResourceManager.GetString("CAMPO_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña modificada con exito.
        /// </summary>
        public static string CONTRASENA_MODIFICADA {
            get {
                return ResourceManager.GetString("CONTRASENA_MODIFICADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya esta registrado.
        /// </summary>
        public static string ERROR_AGREGAR_USUARIO {
            get {
                return ResourceManager.GetString("ERROR_AGREGAR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no coinciden.
        /// </summary>
        public static string ERROR_COINCIDIR_CONTRASENA {
            get {
                return ResourceManager.GetString("ERROR_COINCIDIR_CONTRASENA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es incorrecta.
        /// </summary>
        public static string ERROR_CONTRASENA {
            get {
                return ResourceManager.GetString("ERROR_CONTRASENA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud minima es de 8 caracteres.
        /// </summary>
        public static string ERROR_CONTRASENA_MINIMA {
            get {
                return ResourceManager.GetString("ERROR_CONTRASENA_MINIMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña es igual a la anterior.
        /// </summary>
        public static string ERROR_CONTRASENAS_IGUALES {
            get {
                return ResourceManager.GetString("ERROR_CONTRASENAS_IGUALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta agregada con exito.
        /// </summary>
        public static string TARJETA_AGREGADA {
            get {
                return ResourceManager.GetString("TARJETA_AGREGADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario agregado con exito.
        /// </summary>
        public static string USUARIO_AGREGADO {
            get {
                return ResourceManager.GetString("USUARIO_AGREGADO", resourceCulture);
            }
        }
    }
}
