//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krisa {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krisa.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se admiten solo letras.
        /// </summary>
        public static string CAMPO_LETRAS {
            get {
                return ResourceManager.GetString("CAMPO_LETRAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo requerido.
        /// </summary>
        public static string CAMPO_VACIO {
            get {
                return ResourceManager.GetString("CAMPO_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña modificada con exito.
        /// </summary>
        public static string CONTRASENA_MODIFICADA {
            get {
                return ResourceManager.GetString("CONTRASENA_MODIFICADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya esta registrado.
        /// </summary>
        public static string ERROR_AGREGAR_USUARIO {
            get {
                return ResourceManager.GetString("ERROR_AGREGAR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no coinciden.
        /// </summary>
        public static string ERROR_COINCIDIR_CONTRASENA {
            get {
                return ResourceManager.GetString("ERROR_COINCIDIR_CONTRASENA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error en la conexión a la base de datos.
        /// </summary>
        public static string ERROR_CONEXION {
            get {
                return ResourceManager.GetString("ERROR_CONEXION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es incorrecta.
        /// </summary>
        public static string ERROR_CONTRASENA {
            get {
                return ResourceManager.GetString("ERROR_CONTRASENA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud minima es de 8 caracteres.
        /// </summary>
        public static string ERROR_CONTRASENA_MINIMA {
            get {
                return ResourceManager.GetString("ERROR_CONTRASENA_MINIMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nueva contraseña es igual a la anterior.
        /// </summary>
        public static string ERROR_CONTRASENAS_IGUALES {
            get {
                return ResourceManager.GetString("ERROR_CONTRASENAS_IGUALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario agregado con exito.
        /// </summary>
        public static string USUARIO_AGREGADO {
            get {
                return ResourceManager.GetString("USUARIO_AGREGADO", resourceCulture);
            }
        }
    }
}
